all:
  children:
    controllers:
      children:
        mfs:
          hosts:
            10.1.1.1
      vars:
        ansible_connection: ssh
        ansible_user: master
        ansible_ssh_pass: m2
        ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o RequestTTY=yes"